# Generated by Django 4.2.30 on 2026-07-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('account', '0004_remove_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Is Employee'),
        ),
    ]
