# Generated by Django 4.0.6 on 2022-10-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_auto_20220917_1553'),
        ('department', '0002_auto_20220917_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoplesoft_id', models.CharField(max_length=8, unique=True)),
                ('fullname', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=255)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='photos/members')),
                ('manager_name', models.CharField(max_length=150)),
                ('manager_peoplesoft_id', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
    ]
