# Generated by Django 4.2.30 on 2026-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoplesoft_id', models.CharField(max_length=8)),
                ('fullname', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=255)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='photos/members')),
                ('manager_name', models.CharField(max_length=150)),
                ('manager_peoplesoft_id', models.CharField(max_length=150)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
