# Generated by Django 4.2.30 on 2026-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'peoplesoft_id'), ('company', 'email')},
        ),
    ]
