# Generated by Django 4.0.6 on 2022-11-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_members_date_joined'),
        ('department', '0002_auto_20220917_1552'),
        ('team', '0002_auto_20220917_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='photos/categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=16, unique=True)),
                ('bitlocker_key', models.CharField(blank=True, max_length=200)),
                ('resource_availability', models.CharField(max_length=200)),
                ('resource_description', models.TextField(blank=True, max_length=300)),
                ('added_by', models.CharField(max_length=200)),
                ('resource_image', models.ImageField(blank=True, null=True, upload_to='photos/resources')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resource_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.category')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
                ('resource_status', models.CharField(max_length=200)),
                ('taken_date', models.DateField(auto_now_add=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('peoplesoft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
