# Generated by Django 4.0.6 on 2022-10-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20220917_1552'),
        ('members', '0001_initial'),
        ('team', '0002_auto_20220917_1553'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
                ('device_status', models.CharField(max_length=200)),
                ('taken_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('peoplesoft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
