# Generated by Django 4.0.6 on 2022-10-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('resource', '0003_remove_resourcetaken_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard', models.CharField(blank=True, max_length=100)),
                ('mouse', models.CharField(blank=True, max_length=100)),
                ('network_adapter', models.CharField(blank=True, max_length=100)),
                ('headset', models.CharField(blank=True, max_length=100)),
                ('other_notes', models.TextField(blank=True, max_length=300)),
                ('peoplesoft_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
            ],
        ),
    ]
