# Generated by Django 4.0.6 on 2022-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetaken',
            name='other_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
