# Generated by Django 4.0.6 on 2022-12-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_resourcetaken_other_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetaken',
            old_name='other_notes',
            new_name='reason_notes',
        ),
    ]
