# Generated by Django 4.0.6 on 2022-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_rename_other_notes_resourcetaken_reason_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetaken',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
