# Generated by Django 4.0.6 on 2022-09-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]
    
    def insert_default_terms(apps,schema_editor):
        Team=apps.get_model('team', 'Team')
        Department=apps.get_model('department', 'Department')
        team = Team(team_name='IT Superadmin Management', team_head='Superadmin', department=Department.objects.get(department_name='IT Infrastructure Delivery Services'), team_description='A Super Administrator is a user who has complete access to all objects, folders, role templates, and groups in the system. A deployment can have one or more Super Administrators. A Super Administrator can create users, groups, and other super administrators.', created_by='Superadmin')
        team.save()

    operations = [
        migrations.RunPython(insert_default_terms),
    ]
