# Generated by Django 4.2.30 on 2026-07-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityentry',
            options={'ordering': ['-created_on', '-id']},
        ),
    ]
