# Generated by Django 4.2.30 on 2026-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('team', '0001_initial'),
        ('department', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=200)),
                ('created_ps_id', models.CharField(max_length=200)),
                ('request_resource', models.CharField(max_length=200)),
                ('asset_id', models.CharField(blank=True, max_length=20)),
                ('request_category', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=200)),
                ('request_decription', models.TextField(max_length=300)),
                ('request_response', models.TextField(blank=True, max_length=300)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'unique_together': {('company', 'request_id')},
            },
        ),
    ]
