# Generated by Django 4.2.30 on 2026-07-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resource_bitlocker_key_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='request_resource',
        ),
        migrations.AddField(
            model_name='ticket',
            name='regarding_resource_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='resources.resourcetaken'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='request_category',
            field=models.CharField(choices=[('Request new', 'Request new'), ('Replacement', 'Replacement'), ('Support', 'Support')], max_length=200),
        ),
    ]
