# Generated by Django 4.2.30 on 2026-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_request_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='processing_started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
