# Generated by Django 4.2.30 on 2026-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('employees', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='photos/categories')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='OtherAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_notes', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=16)),
                ('model_name', models.CharField(max_length=200)),
                ('bitlocker_key', models.CharField(blank=True, max_length=200)),
                ('resource_availability', models.CharField(max_length=200)),
                ('resource_description', models.TextField(blank=True, max_length=300)),
                ('added_by', models.CharField(max_length=200)),
                ('resource_image', models.ImageField(blank=True, null=True, upload_to='photos/resources')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_category', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
                ('assigned_by', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_status', models.CharField(max_length=200)),
                ('taken_date', models.DateField(auto_now_add=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason_notes', models.TextField(blank=True, max_length=300)),
                ('manager_peoplesoft_id', models.CharField(blank=True, max_length=200)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('peoplesoft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
