# Generated by Django 4.2.30 on 2026-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('employees', '0002_initial'),
        ('companies', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetaken',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AddField(
            model_name='resource',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.category'),
        ),
        migrations.AddField(
            model_name='otheraccessories',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='otheraccessories',
            name='peoplesoft_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('company', 'asset_id')},
        ),
    ]
