# Generated by Django 4.0.6 on 2022-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_resourcetaken_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetaken',
            name='resource_category',
            field=models.CharField(max_length=200),
        ),
    ]
