# Generated by Django 4.2.30 on 2026-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='bitlocker_key',
        ),
        migrations.RemoveField(
            model_name='resourcetaken',
            name='resource_category',
        ),
        migrations.AddField(
            model_name='category',
            name='attribute_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='tracks_physical_asset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='attribute_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'resource_category')},
        ),
    ]
