# Generated by Django 4.2.30 on 2026-07-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resource_bitlocker_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
