# Generated by Django 4.0.6 on 2022-12-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_date_joined'),
        ('resource', '0008_resourcetaken_assigned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_notes', models.TextField(blank=True, max_length=300)),
                ('peoplesoft_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
            ],
        ),
    ]
