# Generated by Django 4.0.6 on 2022-09-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]
    
    def insert_default_terms(apps,schema_editor):
        Department=apps.get_model('department', 'Department')
        department = Department(department_name='IT Infrastructure Delivery Services', department_head='Superadmin', department_description='Included in this definition are computer labs, classroom technologies, software systems, computing and electronic communications devices and services, e-mail, networks, telephones (including cellular), voice mail, fax transmissions, video, and multimedia.', created_by='Superadmin')
        department.save()

    operations = [
        migrations.RunPython(insert_default_terms),
    ]
